name: Build font

on:
  workflow_dispatch:

jobs:
  build-font:
    name: Build font
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.38"
      - name: Setup node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20.12.2
          cache: 'yarn'
      - name: Install deps
        run: yarn
      - name: Build fontforge
        run: git clone https://github.com/fontforge/fontforge.git
      - name: one
        run: sudo apt-get install libjpeg-dev libtiff5-dev libpng-dev libfreetype6-dev libgif-dev libgtk-3-dev libxml2-dev libpango1.0-dev libcairo2-dev libspiro-dev libwoff-dev python3-dev ninja-build cmake build-essential gettext
      - name: two
        run: |
            cd fontforge
            mkdir build
            cd build
            cmake -GNinja ..
            ninja
            sudo ninja install
      - name: Install fontforge
        run: sudo apt-get install fonttools fontforge python3-fontforge
      - name: Build
        run: make
