name: Build font

on:
  workflow_dispatch:

jobs:
  build-font:
    name: Build font
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Setup Python 3.12.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.38"

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20.12.2
          cache: 'yarn'

      - name: Install Node.js dependencies via yarn
        run: |
          yarn install

      # - name: Install build dependencies for FontForge
      #   run: |
      #     # Install required libraries to build FontForge
      #     brew install \
      #       automake \
      #       libtool \
      #       pkg-config \
      #       cairo \
      #       pango \
      #       icu4c \
      #       fontconfig \
      #       harfbuzz \
      #       libpng \
      #       libspiro \
      #       freetype \
      #       fonttools \
      #       python@3.12

      # - name: Clone FontForge repository
      #   run: |
      #     # Clone FontForge repository and checkout the latest stable version
      #     git clone https://github.com/fontforge/fontforge.git
      #     cd fontforge
      #     git checkout master # You can also checkout a release tag if needed

      # - name: Build FontForge from source
      #   run: |
      #     # Build FontForge from source
      #     cd fontforge
      #     make
      #     sudo make install

      # - name: Install FontForge Python bindings
      #   run: |
      #     # Install FontForge Python bindings
      #     sudo python3 -m pip install --upgrade pip
      #     sudo python3 -m pip install fontforge

      # - name: List installed packages and check Python 3.12
      #   run: |
      #     # Check Python installation
      #     which python3
      #     python3 --version
          
      #     # Check if FontForge binary is installed
      #     which fontforge
      #     fontforge --version
          
      #     # Ensure FontForge Python bindings can be imported
      #     python3 -c "import fontforge; print('FontForge is working!')"

      - name: Install fontforge
        run: brew install fonttools ttfautohint fontforge --with-python

      - name: Build font
        run: make
